---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-app
spec:
  replicas: 5
  selector:
    matchLabels:
      name: go-web-app
  template:
    metadata:
      labels:
        name: go-web-app
    spec:
      containers:
      - name: application
        image: 176548991973.dkr.ecr.us-west-2.amazonaws.com/devops1:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000
