apiVersion: v1
kind: Service
metadata:
  labels:
    app: golangsvc
  name: golangsvc
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: golangsvc
  type: NodePort
